// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkoWcMnf6wI9tOKlJ3-G6N35nyjEmZqGM',
    appId: '1:233219634399:web:bedbd21df51f5d7a0d656a',
    messagingSenderId: '233219634399',
    projectId: 'agro-app-aa23a',
    authDomain: 'agro-app-aa23a.firebaseapp.com',
    storageBucket: 'agro-app-aa23a.firebasestorage.app',
    measurementId: 'G-NDGG193W0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpa0q3tKlf0NSZLzYEkJblDCpUH2kcfeI',
    appId: '1:233219634399:android:30c3b218b768751b0d656a',
    messagingSenderId: '233219634399',
    projectId: 'agro-app-aa23a',
    storageBucket: 'agro-app-aa23a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtHT4UxDuv4zr_VnzvqQcYLbLZEwOp4h8',
    appId: '1:233219634399:ios:892f8a5f2274bdf40d656a',
    messagingSenderId: '233219634399',
    projectId: 'agro-app-aa23a',
    storageBucket: 'agro-app-aa23a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtHT4UxDuv4zr_VnzvqQcYLbLZEwOp4h8',
    appId: '1:233219634399:ios:892f8a5f2274bdf40d656a',
    messagingSenderId: '233219634399',
    projectId: 'agro-app-aa23a',
    storageBucket: 'agro-app-aa23a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkoWcMnf6wI9tOKlJ3-G6N35nyjEmZqGM',
    appId: '1:233219634399:web:f81270c06fe8e5310d656a',
    messagingSenderId: '233219634399',
    projectId: 'agro-app-aa23a',
    authDomain: 'agro-app-aa23a.firebaseapp.com',
    storageBucket: 'agro-app-aa23a.firebasestorage.app',
    measurementId: 'G-9XE563ZH67',
  );
}
